### ISSUE TITLE
Configuration from text file

### ISSUE THREAD

**Issue by KaterinaIvashchenko** [KaterinaIvashchenko/GraduationJavaProject#2]
Support configuration from files: web-server.properties and web-server.xml.
1. Ability to fill all ServerConfig fields.
2. Set file path in Server.start() method.
3. Autoload from classpath.
4. Ability to map handlers to resources.

**Comment by XMitya** [comment]
Please close at it duplicates https://github.com/KaterinaIvashchenko/GraduationJavaProject/issues/3
